// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "brandKit": {
    "empty": "暂无品牌套件",
    "selector": {
      "invalid": "品牌套件: 已失效",
      "none": "品牌套件: 无"
    },
    "title": "品牌套件"
  },
  "canvas": {
    "bottomBar": {
      "backgroundColor": "画布背景色",
      "closeColorPicker": "关闭颜色选择器",
      "fitAll": "显示全部",
      "setBackground": "设置背景为 {{color}}",
      "zoomIn": "放大",
      "zoomOut": "缩小"
    },
    "closeFiles": "关闭生成文件面板",
    "closeLayers": "关闭图层面板",
    "contextMenu": {
      "copyImageFailed": "图片复制失败",
      "copyImageSuccess": "图片已复制",
      "downloadImage": "下载图片",
      "native": {
        "canvasAndShapeProperties": "画布和形状属性",
        "copyImage": "复制图片",
        "copyLinkToObject": "复制对象链接",
        "cropImage": "裁剪图片",
        "duplicate": "复制节点",
        "paste": "粘贴",
        "selectAll": "全选",
        "snapToObjects": "吸附到对象",
        "toggleGrid": "显示/隐藏网格",
        "viewMode": "视图模式",
        "wrapSelectionInFrame": "用画框包裹选区",
        "zenMode": "禅模式"
      }
    },
    "empty": "输入你的想法开始创作",
    "files": {
      "download": "下载 {{name}}",
      "downloadFailed": "下载失败",
      "downloadSuccess": "下载成功",
      "empty": "暂无生成文件",
      "end": "到底了",
      "noPreview": "无预览",
      "title": "已生成文件列表"
    },
    "layers": {
      "empty": "画布为空",
      "title": "图层"
    },
    "logoMenu": {
      "archive": "归档当前项目",
      "archiveConfirm": "确认归档?",
      "archiveFailed": "项目归档失败",
      "duplicate": "复制对象",
      "fitAll": "显示画布所有元素",
      "home": "首页",
      "importImage": "导入图片",
      "menu": "菜单",
      "newProject": "新建项目",
      "projects": "项目库",
      "redo": "重做",
      "undo": "撤销"
    },
    "project": {
      "renameFailed": "项目重命名失败",
      "untitled": "未命名"
    },
    "tools": {
      "arrow": "箭头 (A)",
      "ellipse": "椭圆 (O)",
      "freedraw": "画笔 (P)",
      "generateFailed": "生成失败",
      "generateImage": "AI 生成图片",
      "generateVideo": "AI 生成视频",
      "generating": "生成中...",
      "hand": "拖拽画布 (H)",
      "image": "上传图片",
      "imagePanel": {
        "close": "关闭图片生成面板",
        "deleteCard": "删除图片生成器卡片",
        "generate": "生成",
        "placeholder": "描述你想创建的图片...",
        "title": "AI 图片"
      },
      "line": "直线 (L)",
      "rectangle": "矩形 (R)",
      "selection": "选择 (V)",
      "text": "文字 (T)",
      "videoPanel": {
        "deleteCard": "删除视频生成器卡片"
      }
    }
  },
  "chat": {
    "actions": {
      "collapsePanel": "收起面板",
      "openSettings": "打开设置",
      "resizePanel": "调整聊天面板宽度"
    },
    "agentModelSelector": {
      "apiProvider": "API provider",
      "assistantMode": "助手模式",
      "connectTuttiManaged": "去设置连接",
      "customModelId": "自定义模型 ID",
      "localAgent": "本地 Agent",
      "localAssistant": "本地助手",
      "noApiProviderModels": "未配置 API provider 模型。",
      "noLocalCliModels": "未检测到本地 CLI 模型。",
      "noTuttiManagedModels": "未连接 Tutti Managed 模型。",
      "openSettings": "打开 Agent 设置",
      "settings": "设置",
      "tooltip": "选择 Agent 模型",
      "tuttiManaged": "Tutti Managed",
      "useCustomModel": "使用自定义模型",
      "usesConfiguredDefaultRoute": "使用你配置的默认路由",
      "usesDefaultModel": "使用默认模型：{{model}}"
    },
    "assistant": {
      "title": "AI Media Canvas 助手"
    },
    "conversation": "对话",
    "input": {
      "ariaLabel": "输入消息",
      "attachImages": "添加图片",
      "modelPreference": "图片/视频模型",
      "placeholder": "从一个想法开始，或输入 “@” 提及内容",
      "send": "发送消息"
    },
    "mediaModelPreference": {
      "configure": "配置媒体模型",
      "description": {
        "autoImage": "AI Media Canvas 会使用内置本地渲染器处理图片任务。",
        "autoVideo": "AI Media Canvas 会使用本地视频规划预设处理分镜和动态任务。",
        "manualImage": "AI Media Canvas 仍使用本地渲染器，并优先使用你固定的预设。",
        "manualVideo": "AI Media Canvas 会使用你选择的本地视频规划预设。"
      },
      "empty": {
        "image": "未配置可用的图片模型",
        "video": "未配置可用的视频模型"
      },
      "mode": {
        "auto": "自动",
        "manual": "手动"
      },
      "openSettings": "打开媒体设置",
      "tabs": {
        "image": "图片",
        "video": "视频"
      },
      "title": {
        "image": "图片渲染器",
        "video": "视频规划器"
      }
    },
    "mentions": {
      "remove": "移除提及"
    },
    "reconnecting": "连接已断开，正在重连...",
    "selection": {
      "image": "张图片",
      "images": "张图片",
      "selectedOnCanvas": "已在画布中选中",
      "shape": "个图形",
      "shapes": "个图形"
    },
    "sessions": {
      "cancelDelete": "取消",
      "confirmDelete": "删除",
      "delete": "删除 {{title}}",
      "empty": "暂无对话",
      "history": "历史对话",
      "newChat": "新建对话",
      "noMatches": "无匹配结果",
      "openHistory": "打开历史对话",
      "searchPlaceholder": "请输入搜索关键词"
    },
    "templates": {
      "items": {
        "logoBrand": {
          "label": "Logo 与品牌",
          "prompt": "帮我设计一个 Logo 和品牌视觉方案"
        },
        "marketingBrochure": {
          "label": "营销宣传册",
          "prompt": "帮我设计一套营销宣传册页面，包含封面和内页"
        },
        "productShowcase": {
          "label": "产品展示图",
          "prompt": "帮我设计一组产品展示图，适合电商平台使用"
        },
        "socialCarousel": {
          "label": "社媒轮播图",
          "prompt": "帮我设计一组社交媒体轮播图，包含封面和多张内页，风格统一"
        },
        "socialMedia": {
          "label": "社交媒体",
          "prompt": "帮我设计一张社交媒体海报，风格现代简洁"
        },
        "storyboard": {
          "label": "分镜故事板",
          "prompt": "帮我创建一组分镜故事板，用于展示创意概念"
        }
      },
      "title": "试试这些本地创作模板"
    },
    "thinking": "思考中"
  },
  "common": {
    "actions": {
      "add": "添加",
      "cancel": "取消",
      "clear": "清空",
      "close": "关闭",
      "continue": "继续",
      "copy": "复制",
      "delete": "删除",
      "download": "下载",
      "import": "导入",
      "loading": "加载中...",
      "retry": "重试",
      "save": "保存",
      "search": "搜索",
      "upload": "上传"
    },
    "productName": "AI Media Canvas"
  },
  "errors": {
    "canvas": {
      "loadFailed": "本地画布加载失败。",
      "missingId": "未指定画布 ID。",
      "projectLoadFailed": "项目信息加载失败，请重试。"
    },
    "generic": "出错了",
    "notFound": {
      "backToProjects": "返回项目",
      "message": "页面不存在"
    },
    "pageComponent": "页面组件发生异常，请重试或刷新页面",
    "project": {
      "createFailed": "项目创建失败"
    },
    "refresh": "刷新页面",
    "retry": "重试"
  },
  "generation": {
    "errors": {
      "failed": "生成失败",
      "imageFailed": "图片生成失败，请重试或更换模型。",
      "videoFailed": "视频生成失败，请重试或更换模型。"
    },
    "image": {
      "button": "生成图片",
      "placeholder": "今天我们要创作什么"
    },
    "video": {
      "button": "生成视频",
      "placeholder": "描述你想要的视频镜头、动作、节奏与画面氛围"
    }
  },
  "home": {
    "discovery": {
      "all": "全部",
      "cases": {
        "disc-architecture-01": {
          "prompt": "请以建筑工作室网站概念为起点，设计网站结构、首页视觉、项目展示模块和整体建筑感风格建议。"
        },
        "disc-brand-01": {
          "prompt": "请基于文化艺术中心这个灵感方向，为我做一套品牌探索，输出品牌关键词、主视觉方向、海报延展和社交媒体视觉提案。"
        },
        "disc-character-01": {
          "prompt": "请围绕诡异马戏团角色做一套角色设计，包含角色设定、表情变化、服装元素和场景氛围建议。"
        },
        "disc-illustration-01": {
          "prompt": "参考猫咪塔罗牌这个主题，帮我扩展一套插画系列，给出角色设定、牌面视觉语言、配色建议和延展方向。"
        },
        "disc-poster-01": {
          "prompt": "请围绕复古汽车海报方向设计一组主海报、社媒方图版本和标题排版方案，整体偏胶片感和复古色调。"
        },
        "disc-product-01": {
          "prompt": "围绕机器人机械手产品视觉，帮我设计主视觉构图、材质方向、电商展示图和卖点表达方式。"
        },
        "disc-story-01": {
          "prompt": "基于音乐情绪短片这个方向，帮我做一组 15 到 30 秒分镜，拆出镜头节奏、情绪转场、标题卡和视觉风格建议。"
        },
        "disc-ui-01": {
          "prompt": "请以末日废土风蛋糕店官网为灵感，帮我设计首页信息架构、首屏视觉、商品卡片样式和核心配色建议。"
        }
      },
      "categories": {
        "architecture-design": "建筑设计",
        "branding-design": "品牌设计",
        "character-design": "角色设计",
        "illustration": "插画",
        "poster-and-ads": "海报与广告",
        "product-design": "产品设计",
        "storyboard-video": "影片与分镜",
        "ui-design": "UI设计"
      },
      "title": "灵感发现"
    },
    "examples": {
      "cases": {
        "branding-cap-logo": {
          "prompt": "请做一张帽子品牌周边 mockup，重点表现 Logo 刺绣、材质触感和潮流感，适合官网商品页首图。",
          "title": "把 Logo 放到帽子上"
        },
        "branding-coffee-merch": {
          "prompt": "请把这个咖啡品牌延展到杯子、纸袋和社媒头像，保持高端但亲和的品牌感，并给出 mockup 构图方向。",
          "title": "设计咖啡店品牌周边"
        },
        "branding-logo-options": {
          "prompt": "请为寿司品牌做一组极简 Logo 探索，输出 3 个方向、颜色建议、应用场景和品牌语气差异。",
          "title": "生成 Logo 方向"
        },
        "design-bauhaus-poster": {
          "prompt": "请为音乐节设计一张 Bauhaus 风格海报，使用几何形、强节奏排版和有限色板，并附带移动端竖版延展建议。",
          "title": "设计 Bauhaus 风格海报"
        },
        "design-ceramic-dinnerware": {
          "prompt": "请围绕北欧极简与侘寂气质，做一组陶瓷器皿视觉提案，包含碗、盘、杯的统一造型语言和产品展示图方向。",
          "title": "设计陶瓷餐具套装"
        },
        "design-furniture": {
          "prompt": "请围绕一把雕塑感橙色天鹅绒单椅，输出家具概念海报、材质细节特写和电商主图方向。",
          "title": "尝试家具设计概念"
        },
        "illustration-cat-tarot": {
          "prompt": "请围绕猫咪塔罗牌扩展一套插画系列，补齐角色设定、牌面视觉语言、边框系统和周边延展建议。",
          "title": "扩展猫咪塔罗牌系列"
        },
        "illustration-character-poster": {
          "prompt": "请做一张角色海报，把人物设定、色彩性格和辅助道具统一起来，适合潮流玩具品牌介绍页。",
          "title": "创作趣味角色海报"
        },
        "illustration-seaside-story": {
          "prompt": "请把一个海边奇遇故事画成梦幻插画，强调色彩氛围、光影层次和封面标题位置。",
          "title": "绘制梦幻海边故事"
        },
        "storyboard-comic-sequence": {
          "prompt": "请把原创角色在雨夜屋顶追逐并跃过霓虹招牌的动作场景拆成漫画式连续分镜，保持统一角色动作关系，并且适合后续转成短视频 animatic。",
          "title": "创建漫画式连续分镜"
        },
        "storyboard-music-teaser": {
          "prompt": "请为 15 秒音乐 teaser 规划镜头顺序、情绪节奏、字幕节拍和结尾 logo 出现方式。",
          "title": "搭建音乐 teaser 镜头序列"
        },
        "storyboard-product-teaser": {
          "prompt": "请帮我拆一个 6 镜头产品 teaser 分镜，重点是节奏起伏、转场方式和最后的标题卡落点。",
          "title": "规划 6 格产品 teaser 分镜"
        },
        "ui-ai-waitlist": {
          "prompt": "请设计一个 AI 产品 waitlist 页面，强调未来感、可信感和转化路径，适合 desktop 与移动端首屏适配。",
          "title": "搭建 AI 产品 waitlist 页面"
        },
        "ui-cake-shop": {
          "prompt": "请为末日废土风蛋糕店设计首页，输出首屏视觉、商品卡片和 CTA 样式，整体既怪诞又有趣。",
          "title": "创建蛋糕店落地页"
        },
        "ui-fintech-dashboard": {
          "prompt": "请给我一个金融产品首页首屏方案，突出数据可信感、行动按钮层级和卡片式指标布局。",
          "title": "设计金融仪表盘首屏"
        },
        "visual-engineering-drawings": {
          "prompt": "请把这个产品概念变成一套专业工程蓝图视觉，输出主视图、等轴图、关键尺寸标注和注释层级，适合给研发或打样沟通。",
          "title": "生成专业工程图"
        },
        "visual-magazine-cover": {
          "prompt": "请把这张自拍扩展成时尚杂志封面方案，保留人物神态，补齐封面主标题、副标题、配色和版式层级，整体更高级、更 editorial。",
          "title": "把自拍变成杂志封面"
        },
        "visual-superhero-comic": {
          "prompt": "请设计一页复古超级英雄漫画：原创城市英雄在夜晚街区救援，包含 4 到 6 格分镜、对白气泡、旁白框、动作线和统一人物动作，整体要有 70 年代漫画纸感。",
          "title": "制作经典超级英雄漫画"
        }
      },
      "categories": {
        "branding": "品牌",
        "design": "设计",
        "illustration": "插画",
        "storyboard-video": "分镜",
        "ui-design": "UI 设计",
        "visual-concepts": "视觉概念"
      }
    },
    "hero": {
      "subtitle": "你的本地 AI 设计助手，从想法到作品。",
      "title": "让创意设计更简单"
    },
    "prompt": {
      "attachImages": "添加图片",
      "clear": "清除",
      "modelPreference": "图片/视频模型",
      "placeholder": "让 AI Media Canvas 帮你设计...",
      "submit": "提交 prompt"
    },
    "recentProjects": {
      "archive": "归档 {{name}}",
      "newProject": "新建项目",
      "title": "最近项目",
      "untitled": "未命名",
      "updatedAt": "更新于 {{date}}",
      "viewAll": "查看全部"
    }
  },
  "navigation": {
    "brandKit": "品牌套件",
    "home": "首页",
    "mainNavigation": "主导航",
    "mainRegion": "主内容",
    "projects": "项目",
    "settingsMenu": {
      "description": "打开 Agent 和媒体 provider 的本地设置。",
      "localUser": "本地用户",
      "open": "打开设置菜单",
      "settings": "设置"
    },
    "skills": "技能",
    "skipToMain": "跳到主内容"
  },
  "projects": {
    "archive": "归档 {{name}}",
    "archiveAction": "归档项目",
    "archiveConfirmDescription": "确定归档此项目？它会从项目列表中移除，但本地数据仍会保留。",
    "create": "新建项目",
    "createDialog": {
      "creating": "创建中...",
      "descriptionLabel": "描述（可选）",
      "descriptionPlaceholder": "简单描述一下...",
      "failed": "项目创建失败，请重试。",
      "nameLabel": "名称",
      "namePlaceholder": "我的项目",
      "slugTaken": "已经存在同名项目，请换一个名称。",
      "success": "项目创建成功",
      "title": "新建项目"
    },
    "loadFailed": "本地项目加载失败，请重试。",
    "title": "项目",
    "untitled": "未命名",
    "updatedAt": "更新于 {{date}}"
  },
  "settings": {
    "agentSettings": {
      "actions": {
        "saving": "保存中..."
      },
      "api": {
        "addModel": "添加",
        "addProviderModel": "添加 {{provider}} 模型",
        "browseModels": "浏览可用模型",
        "chooseApiProviderModelBelow": "请在下方选择 API provider 模型。",
        "chooseModel": "选择模型",
        "customProvider": "自定义 provider",
        "defaultLlmModel": "默认 LLM 模型",
        "defaultModelDescription": "从下方已配置的模型列表中选择工作区默认模型。",
        "defaultModelTitle": "默认模型",
        "getApiKey": "获取 {{provider}} API Key",
        "importDetected": "导入已检测模型",
        "noApiProviderModelSelected": "未选择 API provider 模型",
        "noModelsYet": "暂无模型",
        "noProviderModels": "{{provider}} 暂未配置模型。",
        "protocolCredentials": "协议凭证",
        "protocolDescription": "选择一个协议来编辑对应凭证。",
        "providerModels": "{{provider}} 模型",
        "providerModelsDescription": "添加、编辑或移除这个 provider 对外暴露的模型 ID。",
        "quickFillProvider": "快速填充 provider",
        "removeModel": "移除",
        "useModel": "使用 {{model}}",
        "workspaceModels": "工作区模型",
        "workspaceModelsDescription": "从各 provider 下已配置的模型列表中选择。"
      },
      "feedback": {
        "installFailed": "无法安装本地 Agent provider。",
        "updateFailed": "本地 Agent 设置更新失败，请重试。",
        "updated": "本地 Agent 设置已更新。"
      },
      "local": {
        "customModelId": "自定义模型 ID",
        "customModelPlaceholder": "例如 my-model",
        "customOption": "自定义（在下方输入）...",
        "description": "选择生成任务要使用的 CLI 路由。",
        "detectedCli": "已检测 CLI",
        "empty": "暂未检测到本地 CLI 模型。安装或登录支持的本地 CLI 后重新扫描。",
        "fetchedDescription": "当 CLI 暴露模型列表时会自动获取。自定义模式允许输入该 CLI 支持的任意模型 ID。",
        "installHint": "安装 Codex 或 Claude Code 后重新扫描，即可启用本地 Agent 路由。",
        "installRequired": "需要安装",
        "installing": "安装中...",
        "modelCountOne": "{{modelCount}} 个模型",
        "modelCountOther": "{{modelCount}} 个模型",
        "modelLabel": "模型",
        "noCliSelected": "未选择 CLI",
        "rescan": "重新扫描",
        "selectCliFirst": "请先选择 CLI...",
        "selectModel": "选择模型..."
      },
      "source": {
        "apiProvider": "API provider",
        "detected": "已检测 {{cliCount}} 个",
        "localAgent": "本地 Agent",
        "tuttiManaged": "Tutti Managed"
      },
      "tuttiManaged": {
        "bridgeUnavailable": "请在 Tutti 中打开 AI Media Canvas 后授权托管模型。",
        "chooseModel": "请在下方选择 Tutti Managed 模型。",
        "connect": "连接",
        "connectFirst": "连接 Tutti Managed 后导入可用模型。",
        "connected": "已连接",
        "defaultModel": "默认模型",
        "description": "使用由 Tutti 托管的模型凭证，不在当前应用中保存 provider key。",
        "disconnect": "断开",
        "emptyModels": "暂无可用的 Tutti Managed 模型。请在 Tutti 设置中配置 provider。",
        "feedback": {
          "connectFailed": "无法连接 Tutti Managed 模型。",
          "connected": "Tutti Managed 模型已连接。",
          "disconnectFailed": "无法断开 Tutti Managed 模型。",
          "disconnected": "Tutti Managed 模型已断开。",
          "openSettingsFailed": "无法打开 Tutti 设置。"
        },
        "manageInTutti": "在 Tutti 中管理",
        "noModelSelected": "未选择 Tutti Managed 模型",
        "notConnected": "未连接",
        "reauthorize": "重新授权",
        "title": "Tutti Managed"
      }
    },
    "dialogTitle": "设置",
    "general": {
      "description": "控制界面语言与本地显示偏好。",
      "languageDescription": "会保存到本地浏览器，并在后续打开时继续使用。",
      "languageLabel": "语言",
      "languageOptions": {
        "en": "English",
        "zhCN": "简体中文"
      },
      "title": "通用"
    },
    "media": {
      "actions": {
        "save": "保存",
        "saving": "保存中..."
      },
      "affectedModels": "受影响模型",
      "agnesHint": {
        "description": "Agnes 提供免费的入门路由。",
        "free": "免费",
        "getKey": "获取 Agnes API Key",
        "quickStart": "快速开始文档"
      },
      "capabilities": {
        "image": "图片",
        "imageVideo": "图片 + 视频"
      },
      "cards": {
        "agnes": {
          "summary": "Agnes 多模态路由。通过 agnes-ai-cli 提供图片/视频生成能力，包括 compose 与支持关键帧的视频模式。"
        },
        "google": {
          "summary": "Google AI Studio / Developer API 路由，适合 Nano Banana 和 Google 官方图片/视频模型系列。"
        },
        "openai": {
          "summary": "OpenAI 兼容图片路由，复用 OpenAI 兼容 Agent 协议的 key/base URL 配置。"
        },
        "replicate": {
          "summary": "第三方托管模型路由，适合 Seedream、Seedance、Kling，或经 Replicate 路由的 Veo/Sora 系列。"
        },
        "vertex": {
          "summary": "Google Cloud 托管路由。使用 Vertex project 与 location，服务账号凭证仍来自环境变量。"
        },
        "volces": {
          "summary": "字节跳动 / 火山引擎官方通道，用于通过 Ark 提供的豆包 Seedream 模型。"
        }
      },
      "description": "按平台配置图片与视频提供商。如果同一模型家族后续存在多个平台版本，AIMC 会按提供商范围的模型 ID 分开保存，方便你显式选择路由。",
      "feedback": {
        "updateFailed": "本地媒体提供商设置更新失败，请重试。",
        "updated": "本地媒体提供商设置已更新。"
      },
      "localStorageNote": "这些值会保存在本地 sqlite 设置数据库中，并被对应媒体提供商复用。",
      "providerNotes": {
        "replicate": "{{provider}} 是第三方托管平台。",
        "volces": "{{provider}} 是字节跳动 / 火山引擎官方通道。"
      },
      "status": {
        "configured": "已配置",
        "notConfigured": "未配置"
      },
      "title": "媒体提供商"
    },
    "modelConfiguration": {
      "configureAgent": "配置 Agent",
      "configureMedia": "配置媒体模型",
      "description": "Agnes 提供免费的文本、生图、生视频模型能力，可以申请 API Key 后配置。",
      "getAgnesKey": "申请 Agnes API Key",
      "missing": "未配置 {{models}}",
      "models": {
        "agent": "Agent 模型",
        "image": "图片模型",
        "video": "视频模型"
      }
    },
    "status": {
      "loadFailed": "本地设置加载失败，请重试。",
      "loadUnavailable": "当前无法加载本地设置。",
      "unsaved": "有未保存更改",
      "upToDate": "设置已是最新"
    },
    "tabs": {
      "agent": {
        "description": "LLM 协议与默认模型",
        "label": "Agent"
      },
      "general": {
        "description": "语言与界面偏好",
        "label": "通用"
      },
      "media": {
        "description": "图片与视频提供商路由",
        "label": "媒体"
      }
    },
    "title": "设置"
  },
  "skills": {
    "actions": {
      "cancel": "取消",
      "clear": "清空",
      "delete": "删除",
      "details": "详情",
      "install": "安装到本地",
      "installShort": "安装",
      "uninstall": "卸载"
    },
    "catalog": {
      "canvas-director": {
        "description": "帮助 Agent 先梳理画布结构、镜头顺序和版式层级，再给出下一步操作建议。"
      }
    },
    "createDialog": {
      "addFile": "添加文件",
      "adding": "添加中...",
      "description": "创建新的本地技能来扩展 AI Media Canvas 助手的能力。",
      "descriptionPlaceholder": "简述技能的功能和用途...",
      "fileContentPlaceholder": "文件内容...",
      "invalidPath": "文件路径需要以 scripts/、references/ 或 assets/ 开头。",
      "title": "添加自定义技能",
      "useTemplate": "使用模板"
    },
    "customCard": {
      "add": "添加技能",
      "description": "添加技能以解锁你本地助手的新能力。",
      "title": "添加自定义技能"
    },
    "detail": {
      "attachments": "附属文件",
      "author": "作者",
      "confirmDelete": "确认删除?",
      "files": "附属文件 ({{count}})",
      "files_one": "附属文件 ({{count}})",
      "files_other": "附属文件 ({{count}})",
      "license": "许可证",
      "loading": "正在加载技能详情",
      "updatedAt": "更新日期",
      "version": "版本"
    },
    "empty": {
      "adjustFilters": "尝试调整搜索或筛选条件",
      "installOrImport": "从市场安装一个技能，或导入自己的本地 skill。",
      "noInstalled": "暂无已安装技能",
      "noMatches": "未找到匹配的技能"
    },
    "fields": {
      "category": "分类",
      "description": "描述",
      "descriptionOptional": "描述（可选）",
      "name": "名称",
      "nameOptional": "名称（可选）"
    },
    "filters": {
      "label": "筛选",
      "official": "官方",
      "searchLabel": "搜索技能",
      "searchPlaceholder": "搜索技能..."
    },
    "importPanel": {
      "chooseDirectory": "选择目录",
      "chooseFiles": "选择文件",
      "chooseSkill": "选择本地 skill 文件或目录",
      "continueImport": "继续导入",
      "description": "选择本地 `SKILL.md`、skill 文件集合，或直接选择整个 skill 目录。",
      "descriptionPlaceholder": "默认从 SKILL.md 的 Description 段落提取",
      "detectedFile": "已识别 {{path}}",
      "importLocal": "导入到本地",
      "imported": "已导入",
      "importing": "导入中...",
      "namePlaceholder": "默认从 SKILL.md 标题提取",
      "selectedFiles": "已选择 {{count}} 个本地文件",
      "selectedFiles_one": "已选择 {{count}} 个本地文件",
      "selectedFiles_other": "已选择 {{count}} 个本地文件",
      "skippedFiles": "已跳过 {{count}} 个非文本或过大的文件。",
      "skippedFiles_one": "已跳过 {{count}} 个非文本或过大的文件。",
      "skippedFiles_other": "已跳过 {{count}} 个非文本或过大的文件。",
      "suggestion": "建议至少包含一个 SKILL.md 文件，并尽量保留原目录结构。",
      "title": "从本地导入技能",
      "viewInstalled": "查看已安装"
    },
    "marketplace": {
      "alreadyLocal": "已在本地",
      "available": "可安装",
      "empty": "没有找到匹配的本地市场技能。",
      "installed": "已安装",
      "loading": "正在加载本地技能市场...",
      "searchPlaceholder": "搜索本地市场技能..."
    },
    "sources": {
      "community": "社区",
      "system": "官方",
      "user": "自定义"
    },
    "subtitle": "为本地 AI 助手提供可安装、可导入、可启停的技能系统。",
    "tabs": {
      "import": "导入",
      "installed": "已安装",
      "marketplace": "市场"
    },
    "title": "技能",
    "toasts": {
      "created": "技能 \"{{name}}\" 已创建",
      "detailLoadFailed": "技能详情加载失败",
      "importFailed": "导入失败，请检查本地文件内容后重试",
      "imported": "技能 \"{{name}}\" 导入成功",
      "installFailed": "技能安装失败",
      "installed": "技能 \"{{name}}\" 已安装到本地",
      "loadFailed": "本地技能加载失败",
      "noImportableFiles": "没有可导入的文本文件，请选择包含 SKILL.md 的技能目录。",
      "toggleFailed": "技能启停更新失败",
      "uninstallFailed": "技能卸载失败",
      "uninstalled": "技能已卸载"
    }
  }
}
